#!/bin/ash -e

HAPROXY_METRIC_CLASS_TYPE=${HAPROXY_METRIC_CLASS_TYPE:?Need to set HAPROXY_METRIC_CLASS_TYPE}
HAPROXY_METRIC_NAME=${HAPROXY_METRIC_NAME:?Need to set HAPROXY_METRIC_NAME}
HAPROXY_METRIC_CLASS_NAME=${HAPROXY_METRIC_CLASS_NAME:?Need to set HAPROXY_METRIC_CLASS_NAME}
CLOUDWATCH_METRIC_NAMESPACE=${CLOUDWATCH_METRIC_NAMESPACE:?Need to set CLOUDWATCH_METRIC_NAMESPACE}
CLOUDWATCH_METRIC_NAME=${CLOUDWATCH_METRIC_NAME:?Need to set CLOUDWATCH_METRIC_NAME}

HAPROXY_METRIC=$(haproxytool ${HAPROXY_METRIC_CLASS_TYPE} -F /haproxy.sock -m ${HAPROXY_METRIC_NAME} ${HAPROXY_METRIC_CLASS_NAME})

aws cloudwatch put-metric-data \
    --namespace="${CLOUDWATCH_METRIC_NAMESPACE}" \
    --metric-data="MetricName=${CLOUDWATCH_METRIC_NAME},Value=${HAPROXY_METRIC#* },Timestamp=$(date)"

echo "Value ${HAPROXY_METRIC#* } published on cloudwatch metric ${CLOUDWATCH_METRIC_NAMESPACE}:${CLOUDWATCH_METRIC_NAME}"
